.\" Manpage for gitd
.\" Contact benjamin-james@users.noreply.github.com for errors, etc
.TH gitd 1 "16 June 2015" "0.2" "gitd man page"
.SH NAME
gitd \- git commit daemon
.SH SYNOPSIS
gitd
.SH DESCRIPTION
gitd is a daemon that notifies you of commits
.SH OPTIONS
gitd has no options, as it is a daemon, although it loads its configuration from /etc/gitd/gitd.conf.
.SH SEE ALSO
git(1) systemctl(1), fork(2), system(3)
.SH BUGS
No known bugs.
.SH AUTHOR
Benjamin James
