* gitd
A way of notifying you of git commits

It will read subdirectories (specified in the configuration file) to see which repositories to monitor.

You can symlink directories inside the gitd directory so it will fetch to those automatically.

The daemon will fetch from the remote repositories and check if there is a change.

If there is, it will send a notification to the user.

It is a forking daemon, so you don't need to do too much to set it up.

The configuration should usually install to "/etc/gitd/gitd.conf".

Type './autogen.sh', './configure', 'make' and 'sudo make install' to install it in "/usr/local/bin/" and the configuration file to "/usr/local/etc/".
* systemd
Put this into "~/.config/systemd/user/gitd.service":
#+BEGIN_SRC
[Unit]
Description=Gitd: A way of notifying you of git commits

[Service]
Type=forking
ExecStart=/usr/bin/gitd
ExecStop=/usr/bin/pkill gitd
Restart=always

[Install]
WantedBy=default.target
#+END_SRC
And then tell systemd about it:
#+BEGIN_SRC bash
systemctl enable --user gitd.service
systemctl start --user gitd.service
#+END_SRC
* Others
Put it in your ~/.bash_profile to start it at user login
